"""
Regenerate the synthetic PO-extraction fixtures (fictional documents only).

    python tests/fixtures/po/make_fixtures.py

Uses the locally installed Microsoft Edge (or Chrome) in headless mode with a
throwaway profile to print the HTML sources to PDF and to take a screenshot
(PNG) that simulates a scanned page; the image is then wrapped into an
image-only PDF. Nothing is downloaded and nothing leaves this PC.
"""
import os
import shutil
import subprocess
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
CANDIDATES = [
    os.path.expandvars(r'%ProgramFiles(x86)%\Microsoft\Edge\Application\msedge.exe'),
    os.path.expandvars(r'%ProgramFiles%\Microsoft\Edge\Application\msedge.exe'),
    os.path.expandvars(r'%ProgramFiles%\Google\Chrome\Application\chrome.exe'),
]


def browser():
    for c in CANDIDATES:
        if os.path.isfile(c):
            return c
    raise SystemExit('No Edge/Chrome found.')


def run(args, profile):
    subprocess.run([browser(), '--headless=new', '--disable-gpu', '--no-first-run', '--disable-extensions',
                    '--hide-scrollbars', f'--user-data-dir={profile}'] + args, check=True, timeout=120,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def url(name):
    return 'file:///' + os.path.join(HERE, name).replace('\\', '/')


def image_only_pdf(png, pdf, profile):
    """Wrap a PNG into a PDF that has no text layer (simulates a scan)."""
    wrapper = os.path.join(HERE, '_scan_wrapper.html')
    with open(wrapper, 'w', encoding='utf-8') as f:
        f.write('<!DOCTYPE html><html><head><meta charset="utf-8"><style>@page{size:A4;margin:0}html,body{margin:0}'
                f'img{{width:100%;display:block}}</style></head><body><img src="{png}"></body></html>')
    try:
        run(['--no-pdf-header-footer', f'--print-to-pdf={os.path.join(HERE, pdf)}', url('_scan_wrapper.html')], profile)
    finally:
        os.remove(wrapper)


def long_document():
    """62 A4 pages, one item per page, totals on the last page (page-limit test)."""
    head = ('<!DOCTYPE html><!-- SYNTHETIC TEST FIXTURE — generated by make_fixtures.py; fictional supplier. -->'
            '<html lang="en"><head><meta charset="utf-8"><title>Synthetic 62-page quotation</title><style>'
            '@page{size:A4;margin:16mm 14mm}body{font-family:Arial,sans-serif;font-size:10.5pt}.pg{page-break-after:always}'
            '.pg:last-child{page-break-after:auto}table{width:100%;border-collapse:collapse;margin-top:10px}'
            'th,td{border:1px solid #999;padding:5px 6px;text-align:left}td.n{text-align:right}</style></head><body>')
    parts = [head]
    for n in range(1, 63):
        parts.append('<div class="pg">')
        if n == 1:
            parts.append('<div style="font-size:20pt;font-weight:bold">Long Catalogue Supplies Co.</div><p>VAT No: 300555666700003</p>'
                         '<p>Quotation No: LC-62 &nbsp;&nbsp; Date: 23/09/2026</p>')
        parts.append('<table><tr><th>#</th><th>Description</th><th>Unit</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>'
                     f'<tr><td>{n}</td><td>Catalogue item number {n}</td><td>pcs</td><td class="n">1</td>'
                     f'<td class="n">{n * 10}.00</td><td class="n">{n * 10}.00</td></tr></table>')
        if n == 62:
            parts.append('<p>Subtotal: 19,530.00</p><p>VAT 15%: 2,929.50</p><p>Grand Total: 22,459.50</p>')
        parts.append('</div>')
    parts.append('</body></html>')
    with open(os.path.join(HERE, 'quote_long_62p.html'), 'w', encoding='utf-8') as f:
        f.write(''.join(parts))


def main():
    profile = tempfile.mkdtemp(prefix='po-fixture-browser-')
    try:
        long_document()
        for src, out in (('quote_en_multipage.html', 'quote_en_multipage.pdf'), ('quote_ar.html', 'quote_ar.pdf'),
                         ('quote_long_62p.html', 'quote_long_62p.pdf')):
            run(['--no-pdf-header-footer', f'--print-to-pdf={os.path.join(HERE, out)}', url(src)], profile)
        # scanned English quotation (PNG + image-only PDF)
        run(['--window-size=1240,1100', f'--screenshot={os.path.join(HERE, "quote_scan.png")}', url('quote_scan_source.html')], profile)
        image_only_pdf('quote_scan.png', 'quote_scan.pdf', profile)
        # scanned ARABIC quotation: the Arabic document rendered to an image, then image-only PDF
        run(['--window-size=1240,1000', f'--screenshot={os.path.join(HERE, "quote_ar_scan.png")}', url('quote_ar.html')], profile)
        image_only_pdf('quote_ar_scan.png', 'quote_ar_scan.pdf', profile)
        # mixed page: selectable header/totals text + image-only item table
        run(['--window-size=1110,330', f'--screenshot={os.path.join(HERE, "quote_mixed_table.png")}', url('quote_mixed_table_source.html')], profile)
        run(['--no-pdf-header-footer', f'--print-to-pdf={os.path.join(HERE, "quote_mixed.pdf")}', url('quote_mixed.html')], profile)
    finally:
        shutil.rmtree(profile, ignore_errors=True)
    for n in ('quote_en_multipage.pdf', 'quote_ar.pdf', 'quote_scan.png', 'quote_scan.pdf', 'quote_ar_scan.png', 'quote_ar_scan.pdf',
              'quote_mixed_table.png', 'quote_mixed.pdf', 'quote_long_62p.pdf'):
        p = os.path.join(HERE, n)
        print(f'{n:28s} {os.path.getsize(p):>9,d} bytes')


if __name__ == '__main__':
    main()
